import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MediNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
       <div className="max-w-7xl mx-auto ">
<Navbar/>

        {children}
        </div> 
        
        </body>
    </html>
  );
}
