import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./component/shared/Navbar";
import AuthProvider from "@/services/AuthProvider";
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MediNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
    <AuthProvider>
    <div className="">
<Navbar/>

        {children}
        </div> 
    </AuthProvider>
        
        </body>
    </html>
  );
}
