import { Inter } from "next/font/google";

import AuthProvider from "@/services/AuthProvider";
import 'react-toastify/dist/ReactToastify.css';
import DashBoardMenu from "../component/dashboard/DashBoardMenu";
import Navbar from "../component/shared/Navbar";
import DashboardNavbar from "../component/dashboard/DashboardNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MediNext",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (


    <AuthProvider>



        <div className="grid grid-cols-12">
            
     <div className="col-span-3">

     <DashBoardMenu/>
     </div>
            
            <div className="col-span-9">
  
<DashboardNavbar/>
<div className="bg-[#f5f5f5] min-h-screen">



            {children}
            </div>
            </div>
            
            </div>


      
  
    </AuthProvider>
        
      
  );
}
